# change the followings to match your Github username and repo name
baseurl: "" # the name of your github repo
#baseurl: "/blog" # the name of your github repo

url: "https://iservicebus.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title:  Navigate GenAI Adoption Together 
sub-title: You Report the Challenge, We Research the Solution for Free
description: For many developers, Generative AI (GenAI) has been out of reach due to demanding hardware, complex frameworks, and specialized expertise. Language Model as a Service(LMaaS), an open-source platform, changes the game. Leverage your existing programming skills (Java, Javascript, Python, C#) with LMaaS's intuitive OpenAPIs to unlock the power of GenAI directly on your laptop. Easily build GenAI applications and explore best practices with provided libraries and reference implementation. Start your GenAI journey today with LMaaS!

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Jingnan Zhou
author-bio: Executive / entrepreneur / coder  # change to false to hide
site-img: genai_kb.png  # file must be in the /assets/img/ folder
company: Cohesionet

# navigation menu
show-nav-menu: true

nav-menu:
- text: GenAI QA
  permalink: genai-adoption-qa

- text: GenAI Guide
  permalink: genai-adoption-guide
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: https://twitter.com/jingnanzhou
facebook: false
instagram: false
github: https://github.com/iservicebus
linkedin: https://www.linkedin.com/in/jingnanzhou/
medium: false
rss: /feed.xml
google-scholar: false
email: contact@cohesionet.com

# footer information
footer-msg: "Cohesionet"
footer-msg-link: https://www.cohesionet.com

# google analytics
google-analytics: input

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
    - jekyll-feed
